title: Sounds & Pictures content creation
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9436089
  brandStrength: 0.9006445
  lightness: 0.625
  brandColors:
    - '#436276'
    - '#FFFFFF'
    - '#1D1D1B'
    - '#888888'
    - '#E0E0E0'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
name: Sounds & Pictures
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.55408
layout_spectrum: 1
