name: Sounds & Pictures
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55408
title: Sounds & Pictures
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#436373'
    - '#151412'
    - '#c45057'
    - '#8694a0'
    - '#ffffff'
  brandStrength: 0.5625
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
