name: Sounds & Pictures
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#436276'
    - '#FFFFFF'
    - '#1D1D1B'
    - '#888888'
    - '#E0E0E0'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
